apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: default
  destination: 
    namespace: wp
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/JuanBermudezN/argo-kustomize.git
    targetRevision: HEAD
    path: manifests/overlays/prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
